language: go
go:
  - 1.3

notificaitons:
  email:
    recipients: phillipsopaolacoding@gmail.com
    on_success: change
    on_failure: always

script:
  - go test -v ./tests
install:
  - go get github.com/philangist/golang-twisted-steel
